version: '3.1'

services:
  mysqlsrv:
    container_name: mysqlsrv 
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "2020!"
      MYSQL_DATABASE: "payfast"
    ports:
      - "3306:3306"    
